### ISSUE TITLE
Channel and maybe device support in rules

### ISSUE THREAD

**Issue by nstrelow** [josecastroleon/pimatic-pushbullet#10]
I am currently playing around with javascript and coffeescript to get " channel:" working as an argument inside of rules.

**Usecase**: I have to pushes I send, one is my room temp, the other is if someone ranged the door.
The ring notification should also be sent to my flatmate (sent to a channel), but my room temp only to me. Therefore being able to specify " channel:" inside rules would be quite nice.

Here is what I've got working so far:

``` javascript
setChannel = (function(_this) {
        return function(m, tokens) {
          return device = {
            channel_tag: String(tokens).replace("\"", "").replace("\"", "").replace("'","")
          };
        };
      })(this);
```

more like a dirty hack, but I will try to get it into the coffescript.

**Comment by josecastroleon** [comment]
I was thinking in a way to add your installation as a device. So then if you push something to your device it gets parsed by the rules. I can also have a look on putting this as well

**Comment by djnilse** [comment]
I have some working coffeescript now, will open a pull request later, so that you can have a look at it.

If I understand you correctly, I don't think having a device config is actually neccessary for a pushbullet plugin, since it is only triggered by rules.

Also adding new devices requires a restart of pimatic. Adding new rules or modifying them in contrary don't.

Extending the set of possible rules, like adding the api key to the rules, would be nice to have.

**Comment by quintz** [comment]
Is channel working?
Tried it and it won't work :/

**Comment by mwittig** [comment]
I am closing this as both features are supported with version 0.9

@quintz I have just retested the "channel" feature and it works as expected
